### ISSUE TITLE
Is this currently usable, on a 1.12.2 server?

### ISSUE THREAD

**Issue by VariableVixen** [eccentricdevotion/TARDISVortexManipulator#2]
What it says on the tin. I've got a spigot 1.12.2 server with the TARDIS plugin, I'd like to add more DW content, but this hasn't been updated in about a year. Is it usable in 1.12.2? The sonic blaster has been about two years, so that's almost certainly incompatible, but I don't know about this one.

**Comment by eccentricdevotion** [comment]
Sonic Blaster has been abandoned a while now (it was just too overpowered imo, if you can think of a better use let me know...)
Vortex Manipulator works fine, it doesn't use any Bukkit API that needs updating at the moment (last commit was the update to 1.12).
Once Spigot 1.13 is released I'll upload a new version, but the changes are pretty minor...

**Comment by VariableVixen** [comment]
Well, for the blaster, I forget the specifics because I think I came along too late to actually run it, but... what about a block blacklist/whitelist, requiring artron energy to charge the power cells, and only removing blocks for so many seconds, so as to create temporary hole to go through before putting everything back the way it was? That's still probably a _bit_ OP, but it's the best I can think of and it'd be up to server owners if they think it's too strong to add to their server.
